apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: enhanced-
resources:
  - ../../common
images:
  - name: local/transformers-api
    newName: local/transformers-api-enhanced
    newTag: 0.1.0
labels:
  - pairs:
      api-variant: enhanced
    includeTemplates: true
